VALID_CATEGORIES = (
    "ALBUM",
    "CASSETTE",
    "VINYL",
    "MIRROR",
    "POSTER",
    "STICKER",
    "TSHIRT",
    "OTHER",
    "فندک",
)
VALID_CHANNELS = ("INSTAGRAM", "WEBSITE", "WHOLESALE", "IN_PERSON", "OTHER")
VALID_STATUSES = (
    "DRAFT",
    "PENDING",
    "PAID",
    "COMPLETED",
    "CANCELLED",
    "REFUNDED",
)
